name: Splunk Deployment Pipeline
on:
  push:
    branches: [ main ]  # Adjust branch as needed
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-to-splunk-enterprise:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Copy Files to Staging Directory
      run: |
        mkdir -p ${{ github.workspace }}/staging
        cp -r ${{ github.workspace }}/* ${{ github.workspace }}/staging/ || true
      continue-on-error: true
      
    - name: Create and Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DEV_SPLUNK_DEPLOYMENT_SERVER
        path: ${{ github.workspace }}/staging
        retention-days: 30
        
    - name: Copy ServerClass to DEV_SPLUNK_DEPLOYMENT_SERVER
      run: |
        sudo cp ${{ github.workspace }}/staging/serverclass.conf /opt/splunk/etc/system/local
      continue-on-error: true
      
    - name: Copy new splunk apps to DEV_SPLUNK_DEPLOYMENT_SERVER
      run: |
        sudo cp -r ${{ github.workspace }}/staging/deployment-apps/* /opt/splunk/etc/deployment-apps/
      continue-on-error: true
      
    - name: Change Ownership Of Splunk Directory
      run: |
        sudo chown -R splunk:splunk /opt/splunk/
      continue-on-error: true
      
    - name: Reload Deployment Server
      run: |
        sudo /opt/splunk/bin/splunk reload deploy-server -auth admin:password
      continue-on-error: true

  reload-splunk-deployment-server:
    runs-on: ubuntu-latest
    needs: deploy-to-splunk-enterprise  # This job runs after the first job completes
    steps:
    - name: Reload Deployment Server
      run: |
        sudo /opt/splunk/bin/splunk reload deploy-server -auth admin:password
      continue-on-error: true
